// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// knots_selection_cpp
NumericVector knots_selection_cpp(NumericMatrix X, NumericVector y, int m, double lam0);
RcppExport SEXP _vcmasf_knots_selection_cpp(SEXP XSEXP, SEXP ySEXP, SEXP mSEXP, SEXP lam0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type lam0(lam0SEXP);
    rcpp_result_gen = Rcpp::wrap(knots_selection_cpp(X, y, m, lam0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_vcmasf_knots_selection_cpp", (DL_FUNC) &_vcmasf_knots_selection_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_vcmasf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
