# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knots_selection_cpp <- function(X, y, m, lam0) {
    .Call(`_vcmasf_knots_selection_cpp`, X, y, m, lam0)
}

